const links = {
  monthly: 'PAYHIP_MONTHLY_LINK_HERE',
  annual: 'PAYHIP_ANNUAL_LINK_HERE',
  payhip: 'PAYHIP_LINK_HERE',
  email: 'CONTACT_EMAIL_HERE',
};

const navItems = [
  ['How It Works', '#how-it-works'],
  ['Results', '#results'],
  ['Pricing', '#pricing'],
  ['FAQ', '#faq'],
  ['Get Access', '#get-access'],
];

const problemCards = [
  {
    title: 'Less emotional trading',
    text: 'Signals are generated by predefined proprietary rules, not by fear, hype or random market opinions.',
  },
  {
    title: 'BTC-focused logic',
    text: 'The strategy is mainly built around BTC market behaviour, which often leads the broader crypto market.',
  },
  {
    title: 'Can be tested on other crypto',
    text: 'Because ETH and many altcoins often move with BTC, users may also test the strategy on other liquid crypto pairs.',
  },
];

const howCards = [
  {
    title: 'Trend Context',
    text: 'The strategy is designed to analyze whether market conditions support a directional move before showing a signal.',
  },
  {
    title: 'Momentum Confirmation',
    text: 'Signals are filtered through proprietary confirmation logic to avoid reacting to every small market move.',
  },
  {
    title: 'Clear Chart Signals',
    text: 'BUY and SELL labels appear directly on the TradingView chart, helping you follow a clear process instead of relying on emotion.',
  },
];

const includedItems = [
  'Private invite-only TradingView strategy access',
  'BTC-focused trading logic',
  'BUY and SELL signals on chart',
  'Long and short setup visibility',
  'Buy, sell, short and exit/close signal labels if enabled in the script',
  'Usable for testing on ETH and major crypto markets',
  'Setup guide for adding the strategy to TradingView',
  'Basic alert setup guidance',
  'Recommended starting settings',
  'Future strategy updates while subscribed',
  'Access managed through TradingView',
];

const screenshots = [
  ['BTC trend setup example', 'Example of how the strategy can identify structured BTC trend-following setups.'],
  ['BTC chart with BUY and SELL labels', 'Placeholder for a TradingView chart showing clear Bitcoin signals.'],
  ['ETH test example', 'Because ETH often follows the broader crypto market direction, users may test the strategy on ETH pairs as well.'],
  ['Short signal example', 'Example of bearish market conditions where short logic may help identify downside setups.'],
];

const performanceRows = ['BTCUSDT', 'ETHUSDT', 'Other major crypto'];

const steps = [
  ['Choose payment method', 'Pay through Payhip or manually with crypto wallet transfer.'],
  ['Send your TradingView username', 'After payment, submit your TradingView username and payment details.'],
  ['Access is activated manually', 'Your TradingView username is added to the private invite-only script access list.'],
  ['Use it inside TradingView', 'Open TradingView, go to Invite-only scripts, and add the strategy to your chart.'],
];

const monthlyFeatures = [
  'Keep this price while your subscription stays active',
  'Access through TradingView',
  'BTC-first long and short strategy logic',
  'Can be tested on ETH and other liquid crypto markets',
  'Setup guide included',
  'Basic alert instructions',
  'Cancel anytime according to Payhip/payment provider rules',
  'Later price for new users: $39/month',
];

const annualFeatures = [
  'One year of access',
  'TradingView invite-only access included',
  'Setup guide included',
  'Basic alert instructions',
  'Strategy updates while active',
  'Renewal price may change in future',
];

const wallets = [
  ['USDT', 'TRC20 or selected network', 'USDT_WALLET_ADDRESS_HERE', 'Send exact amount or equivalent'],
  ['USDC', 'Polygon or selected network', 'USDC_WALLET_ADDRESS_HERE', 'Send exact amount or equivalent'],
  ['BTC', 'Bitcoin', 'BTC_WALLET_ADDRESS_HERE', 'Send exact amount or equivalent'],
];

const faqs = [
  ['Is this financial advice?', 'No. This strategy is a trading tool for educational and analytical use only. It is not financial advice.'],
  ['Does it guarantee profit?', 'No. No trading strategy can guarantee profit. Trading involves risk, and losses are possible.'],
  ['Do I get the Pine Script source code?', 'No. The source code, exact formula, thresholds, weights and internal rules remain proprietary. You get access to use the private TradingView strategy.'],
  ['Is this strategy only for BTC?', 'The strategy is BTC-first and designed mainly for Bitcoin. Because major crypto markets are often correlated, users may also test it on ETH and other liquid crypto pairs. However, every market should be tested separately before use.'],
  ['Does it support long and short signals?', 'Yes. The system is designed to show both long and short setup signals, depending on the final script version and enabled settings.'],
  ['How do I get access after payment?', 'After payment, send your TradingView username using the access request form. Access is activated manually by adding your username to the invite-only TradingView script.'],
  ['Can I cancel?', 'Yes. Monthly access can be cancelled according to Payhip/payment provider rules. Access remains active while the subscription is active.'],
  ['Can I pay with crypto?', 'Yes. Crypto wallet transfer can be offered manually. Access is granted after payment confirmation.'],
  ['Do you offer refunds?', 'Due to the digital nature of the product, payments are generally non-refundable once access has been activated. If access cannot be provided because of a technical problem, contact support.'],
];

function Button({ href, children, variant = 'primary' }) {
  return (
    <a className={`button ${variant === 'secondary' ? 'buttonSecondary' : ''}`} href={href}>
      {children}
    </a>
  );
}

function SectionHeader({ eyebrow, title, children }) {
  return (
    <div className="sectionHeader">
      {eyebrow && <p className="eyebrow">{eyebrow}</p>}
      <h2>{title}</h2>
      {children && <p>{children}</p>}
    </div>
  );
}

function ScreenshotPlaceholder({ title, description }) {
  return (
    <article className="screenshotCard">
      <div className="chartPlaceholder" role="img" aria-label={title}>
        <div className="chartGrid">
          <span className="signal buy">BUY</span>
          <span className="signal sell">SELL</span>
        </div>
      </div>
      <h3>{title}</h3>
      <p>{description}</p>
    </article>
  );
}

function App() {
  const mailto = `mailto:${links.email}?subject=TradingView%20Strategy%20Access%20Request&body=Name:%0AEmail:%0ATradingView%20username:%0APayment%20method:%0APayhip%20order%20email%20or%20crypto%20transaction%20hash:%0AMessage:`;

  return (
    <>
      <header className="siteHeader">
        <nav className="nav" aria-label="Primary navigation">
          <a className="logo" href="#top" aria-label="BTC Strategy home">BTC Strategy</a>
          <div className="navLinks">
            {navItems.map(([label, href]) => (
              <a href={href} key={label}>{label}</a>
            ))}
          </div>
          <Button href="#get-access">Get Access</Button>
        </nav>
      </header>

      <main id="top">
        <section className="hero section">
          <div className="heroCopy">
            <p className="eyebrow">BTC-first proprietary trend and momentum signal system for TradingView.</p>
            <h1>Bitcoin TradingView Strategy for Clear Crypto Trend Signals</h1>
            <p className="heroLead">
              A BTC-first trading system designed to help you identify long and short setups on Bitcoin and major crypto markets - without emotional guessing.
            </p>
            <p>Built for TradingView. Designed for BTC. Usable for testing on ETH and other liquid crypto pairs.</p>
            <p className="riskLine">No guaranteed profits. Trading involves risk. This is not financial advice.</p>
            <div className="buttonRow">
              <Button href={links.monthly}>Get Founding Member Access</Button>
              <Button href="#crypto-payment" variant="secondary">Pay with Crypto Wallet</Button>
            </div>
            <p className="microcopy">Launch price: $19/month. Later price for new users: $39/month.</p>
          </div>
          <aside className="heroVisual" aria-label="TradingView screenshot placeholder">
            <div className="platformBar">
              <span></span><span></span><span></span>
              <strong>BTCUSDT 4H</strong>
            </div>
            <div className="heroChart" role="img" aria-label="BTC chart screenshot with BUY and SELL signals">
              <span className="signal buy heroBuy">BUY</span>
              <span className="signal sell heroSell">SELL</span>
              <p>BTC chart screenshot with BUY and SELL signals</p>
            </div>
          </aside>
        </section>

        <section className="section" id="problem">
          <SectionHeader title="Most crypto traders do not lose because they lack information. They lose because they lack structure.">
            Crypto markets move fast. Bitcoin can change direction quickly, and emotional decisions often lead to late entries, early exits, overtrading, and chasing candles.
          </SectionHeader>
          <div className="split">
            <div>
              <p>This strategy is built to give traders a structured way to read the market using clear TradingView crypto signals instead of reacting to fear, greed, social media noise or random opinions.</p>
              <ul className="checkList">
                {['Stop guessing where to enter', 'Reduce emotional decision-making', 'Avoid random trades', 'Follow a repeatable signal framework', 'Focus on trend and momentum conditions'].map((item) => <li key={item}>{item}</li>)}
              </ul>
            </div>
            <div className="cardGrid">
              {problemCards.map((card) => (
                <article className="card" key={card.title}>
                  <h3>{card.title}</h3>
                  <p>{card.text}</p>
                </article>
              ))}
            </div>
          </div>
        </section>

        <section className="section band" id="solution">
          <SectionHeader title="A proprietary BTC-first signal system for TradingView">
            This private TradingView strategy uses a proprietary multi-factor trend and momentum confirmation model to identify potential long and short setups. It is designed primarily for Bitcoin, while also being suitable for testing on ETH and other major crypto markets.
          </SectionHeader>
          <p>The exact formula, indicators, weights, thresholds and Pine Script code remain private. You see the signals, setup guidance and chart behavior - not the source code.</p>
          <div className="highlight">BTC-first. Crypto-ready. Proprietary trend signals for TradingView.</div>
        </section>

        <section className="section" id="how-it-works">
          <SectionHeader title="How the system helps you trade" />
          <div className="threeGrid">
            {howCards.map((card) => (
              <article className="card featureCard" key={card.title}>
                <h3>{card.title}</h3>
                <p>{card.text}</p>
              </article>
            ))}
          </div>
        </section>

        <section className="section band" id="what-you-get">
          <SectionHeader title="What you get with access" />
          <ul className="includedList">
            {includedItems.map((item) => <li key={item}>{item}</li>)}
          </ul>
          <p className="riskLine">This is not an automated trading bot. It does not place trades for you. It is a TradingView strategy tool designed to support your own analysis and decision-making.</p>
        </section>

        <section className="section" id="screenshots">
          <SectionHeader title="See the strategy in action">
            Use this section to show real chart examples and historical backtest screenshots. Results should be presented honestly and clearly, without promising future profit.
          </SectionHeader>
          <div className="screenshotGrid">
            {screenshots.map(([title, description]) => (
              <ScreenshotPlaceholder title={title} description={description} key={title} />
            ))}
          </div>
          <p className="smallDisclaimer">Historical results and chart examples are for educational and analytical purposes only. Past performance does not guarantee future results.</p>
        </section>

        <section className="section band" id="results">
          <SectionHeader title="Backtest and performance transparency">
            Performance must be reviewed realistically. Backtests are historical and do not guarantee future results. Results depend on the asset, timeframe, fees, slippage, market conditions and selected settings.
          </SectionHeader>
          <div className="tableWrap">
            <table>
              <thead>
                <tr>
                  {['Market', 'Timeframe', 'Period Tested', 'Net Profit', 'Max Drawdown', 'Profit Factor', 'Number of Trades'].map((heading) => <th key={heading}>{heading}</th>)}
                </tr>
              </thead>
              <tbody>
                {performanceRows.map((market) => (
                  <tr key={market}>
                    <td>{market}</td>
                    <td>4H</td>
                    <td>ADD DATA</td>
                    <td>ADD DATA</td>
                    <td>ADD DATA</td>
                    <td>ADD DATA</td>
                    <td>ADD DATA</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="smallDisclaimer">Always include commission and slippage assumptions when publishing final results.</p>
        </section>

        <section className="section" id="access-process">
          <SectionHeader title="How access works" />
          <div className="stepGrid">
            {steps.map(([title, text], index) => (
              <article className="stepCard" key={title}>
                <span>{index + 1}</span>
                <h3>{title}</h3>
                <p>{text}</p>
              </article>
            ))}
          </div>
        </section>

        <section className="section band" id="pricing">
          <SectionHeader title="Founding Member Launch Offer">
            Early users can lock in launch pricing before the regular monthly price increases for new users.
          </SectionHeader>
          <div className="pricingGrid">
            <PricingCard title="Monthly Access" price="$19/month" label="Founding Member Price" features={monthlyFeatures} cta="Get Monthly Access" href={links.monthly} featured />
            <PricingCard title="Annual Launch Access" price="$149/year" label="Best value for early users" features={annualFeatures} cta="Get Annual Access" href={links.annual} />
          </div>
          <p className="riskLine">Payhip subscriptions can be cancelled according to Payhip/payment provider rules. Crypto payments are manual and prepaid for the selected period.</p>
        </section>

        <section className="section urgency">
          <SectionHeader title="Launch price available for early users only">
            The founding member price is available during the launch period. New users who join later will pay the regular price.
          </SectionHeader>
          <p>Founding monthly members keep the $19/month price for as long as their subscription stays active.</p>
          <Button href={links.monthly}>Lock in Founding Price</Button>
        </section>

        <section className="section band" id="get-access">
          <SectionHeader title="Choose your payment method" />
          <div className="paymentGrid">
            <article className="card paymentCard">
              <h3>Payhip Checkout</h3>
              <p>Use Payhip if you want to pay by card, PayPal, Apple Pay, Google Pay or other available payment methods depending on checkout settings.</p>
              <div className="buttonRow">
                <Button href={links.monthly}>Monthly Access</Button>
                <Button href={links.annual} variant="secondary">Annual Access</Button>
              </div>
              <a className="textLink" href={links.payhip}>General Payhip checkout fallback</a>
            </article>
            <article className="card paymentCard">
              <h3>Crypto Wallet Transfer</h3>
              <p>Use crypto wallet transfer if you prefer to pay manually with crypto. After sending payment, submit your transaction hash, email and TradingView username.</p>
              <Button href="#crypto-payment" variant="secondary">Show Crypto Payment Instructions</Button>
            </article>
          </div>
        </section>

        <section className="section" id="crypto-payment">
          <SectionHeader title="Crypto payment instructions">
            Crypto payments are manual and irreversible. Please check the wallet address and network carefully before sending. Payments sent to the wrong address or wrong network may not be recoverable.
          </SectionHeader>
          <div className="tableWrap">
            <table>
              <thead>
                <tr>
                  {['Currency', 'Network', 'Wallet Address', 'Notes'].map((heading) => <th key={heading}>{heading}</th>)}
                </tr>
              </thead>
              <tbody>
                {wallets.map(([currency, network, wallet, notes]) => (
                  <tr key={currency}>
                    <td>{currency}</td>
                    <td>{network}</td>
                    <td><code>{wallet}</code></td>
                    <td>{notes}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <article className="accessFormCard">
            <h3>Submit access request</h3>
            <form action={mailto} method="post" encType="text/plain">
              <label>Name<input name="Name" autoComplete="name" /></label>
              <label>Email<input name="Email" type="email" autoComplete="email" /></label>
              <label>TradingView username<input name="TradingView username" /></label>
              <label>Payment method<select name="Payment method"><option>Payhip</option><option>Crypto</option></select></label>
              <label>Payhip order email or crypto transaction hash<input name="Payment details" /></label>
              <label>Message<textarea name="Message" rows="4"></textarea></label>
              <button type="submit">Submit Access Request</button>
            </form>
          </article>
        </section>

        <section className="section band" id="faq">
          <SectionHeader title="FAQ" />
          <div className="faqList">
            {faqs.map(([question, answer]) => (
              <details key={question}>
                <summary>{question}</summary>
                <p>{answer}</p>
              </details>
            ))}
          </div>
        </section>

        <section className="section finalCta">
          <SectionHeader title="Trade Bitcoin with more structure">
            Get access to a BTC-first TradingView strategy designed to help identify trend and momentum setups without emotional guessing.
          </SectionHeader>
          <Button href={links.monthly}>Get Founding Member Access</Button>
          <p className="microcopy">$19/month launch price. Later price for new users: $39/month.</p>
        </section>

        <section className="section riskSection" id="risk-disclaimer">
          <SectionHeader title="Risk disclaimer" />
          <p>This website and TradingView strategy are for educational and analytical purposes only. Nothing on this website is financial, investment, trading, tax or legal advice. Trading cryptocurrencies involves significant risk and may result in losses. Past performance, backtests and historical examples do not guarantee future results. You are responsible for your own trading decisions.</p>
          <p>Trading cryptocurrencies involves substantial risk and may result in losses. Past performance, backtests, screenshots and examples do not guarantee future results. This product is not financial advice, investment advice or a recommendation to buy or sell any asset. You are responsible for your own trading decisions, risk management and compliance with local laws.</p>
        </section>
      </main>

      <footer className="footer">
        <div>
          <a className="logo" href="#top">BTC Strategy</a>
          <p>This product is independent and is not affiliated with, endorsed by, or sponsored by TradingView.</p>
        </div>
        <nav aria-label="Footer navigation">
          <a href={`mailto:${links.email}`}>Contact: CONTACT_EMAIL_HERE</a>
          <a href="#risk-disclaimer">Terms of Access</a>
          <a href="#risk-disclaimer">Privacy Policy</a>
          <a href="#risk-disclaimer">Refund Policy</a>
          <a href="#risk-disclaimer">Risk Disclaimer</a>
          <span>Not affiliated with TradingView</span>
        </nav>
      </footer>
    </>
  );
}

function PricingCard({ title, price, label, features, cta, href, featured = false }) {
  return (
    <article className={`pricingCard ${featured ? 'featured' : ''}`}>
      <p className="priceLabel">{label}</p>
      <h3>{title}</h3>
      <p className="price">{price}</p>
      <ul className="checkList">
        {features.map((feature) => <li key={feature}>{feature}</li>)}
      </ul>
      <Button href={href}>{cta}</Button>
    </article>
  );
}

export default App;
